# EINO Service 配置文件

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8003
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

# 数据库配置
database:
  host: "localhost"
  port: 5433
  username: "lyss_user"
  password: "lyss_dev_password_2025"
  database: "lyss_platform"
  ssl_mode: "disable"

# Redis配置
redis:
  host: "localhost"
  port: 6380
  password: ""
  db: 0

# 依赖服务配置
services:
  tenant_service:
    base_url: "http://localhost:8002"
    timeout: "30s"
  memory_service:
    base_url: "http://localhost:8004"
    timeout: "30s"

# 日志配置
logging:
  level: "info"
  format: "json"
  output: "stdout"
  max_size: 100
  max_backups: 3
  max_age: 7

# 凭证管理配置
credential:
  cache_ttl: "5m"
  health_check_interval: "2m"
  max_concurrent_tests: 10

# 工作流配置
workflows:
  max_concurrent_executions: 100
  execution_timeout: "5m"
  default_strategy: "first_available"