# Anthropic供应商配置
provider_id: "anthropic"
name: "Anthropic"
description: "Anthropic Claude系列模型"
icon: "anthropic.png"

# 支持的模型类型
supported_model_types:
  - "llm"

# 凭证配置Schema
credential_schema:
  fields:
    - name: "api_key"
      type: "string"
      required: true
      sensitive: true
      label: "API Key"
      placeholder: "sk-ant-..."
      validation:
        min_length: 20
    - name: "base_url"
      type: "string"
      required: false
      label: "Base URL"
      placeholder: "https://api.anthropic.com"
      default: "https://api.anthropic.com"

# 支持的模型列表
supported_models:
  - model_id: "claude-3-haiku-20240307"
    name: "Claude 3 Haiku"
    type: "llm"
    max_tokens: 200000
    pricing:
      input: 0.00025
      output: 0.00125
  - model_id: "claude-3-sonnet-20240229"
    name: "Claude 3 Sonnet"
    type: "llm"
    max_tokens: 200000
    pricing:
      input: 0.003
      output: 0.015
  - model_id: "claude-3-opus-20240229"
    name: "Claude 3 Opus"
    type: "llm"
    max_tokens: 200000
    pricing:
      input: 0.015
      output: 0.075
  - model_id: "claude-3-5-sonnet-20241022"
    name: "Claude 3.5 Sonnet"
    type: "llm"
    max_tokens: 200000
    pricing:
      input: 0.003
      output: 0.015

# 错误映射
error_mapping:
  connection_error:
    - "anthropic.APIConnectionError"
  authentication_error:
    - "anthropic.AuthenticationError"
  rate_limit_error:
    - "anthropic.RateLimitError"
  quota_exceeded_error:
    - "anthropic.PermissionDeniedError"
  model_not_found_error:
    - "anthropic.NotFoundError"
  bad_request_error:
    - "anthropic.BadRequestError"
  server_error:
    - "anthropic.InternalServerError"

# 默认配置
defaults:
  timeout: 30
  max_retries: 3
  retry_delay: 1